#
# Region Configuration File
#

# Region section
region:
  # Region name
  # Directory of the same name must exists under installation base path
  # The directory must contain these files:
  #   namelist.wps[.template]
  #   namelist.input[.template]
  #   region.yaml
  name: 'PANOCHE'
  # GRIB source name
  # This setting defines what GRIB files to use for this region
  # The source name must be defined in grib.yaml
  grib_source: 'GFS025'
  parent_region: 'PANOCHE'

forecast:
  local_time:
    #for better results this should be less then start hour for higher domain
    start: 9
    end: 16

site_files:
  - sites.json
  - chelan.wpt